/**
 * Kafta Analogue Studio — UI Module
 * Handles: accordion (effect switches), synchronized zoom/pan viewer
 * @developer krafta.
 * @portfolio https://www.facebook.com/krafta.visio
 * @github https://github.com/krafta-visio
 * @version 3.0.0
 * @created 2025
 */

// ─────────────────────────────────────────────────────────────
// ACCORDION — effect cards show/hide when toggle changes
// ─────────────────────────────────────────────────────────────

function initAccordion(){[{toggle:"applyGrainToggle",panel:"grainSettingsPanel"},{toggle:"applyLutToggle",panel:"lutSettingsPanel"},{toggle:"applyBlackMistToggle",panel:"blackMistSettingsPanel"},{toggle:"applyHalationToggle",panel:"halationSettingsPanel"}].forEach(({toggle:e,panel:t})=>{const n=document.getElementById(e),i=document.getElementById(t);n&&i&&(e=()=>{n.checked?i.classList.remove("hidden"):i.classList.add("hidden")},n.addEventListener("change",e),e())})}const viewer={scale:1,tx:0,ty:0,isDragging:!1,startX:0,startY:0,startTx:0,startTy:0};function applyViewerTransform(){var e=`translate(${viewer.tx}px,${viewer.ty}px) scale(${viewer.scale})`,t=document.getElementById("originalTransform"),n=document.getElementById("processedTransform"),t=(t&&(t.style.transform=e),n&&(n.style.transform=e),document.getElementById("zoomLevelDisplay"));t&&(t.textContent=Math.round(100*viewer.scale)+"%")}function doZoom(e,t,n){var e=Math.max(.1,Math.min(16,viewer.scale*e)),i=(t-viewer.tx)/viewer.scale,a=(n-viewer.ty)/viewer.scale;viewer.tx=t-i*e,viewer.ty=n-a*e,viewer.scale=e,applyViewerTransform()}function viewerZoomIn(){var e=document.getElementById("originalPanel");e&&doZoom(1.25,e.clientWidth/2,e.clientHeight/2)}function viewerZoomOut(){var e=document.getElementById("originalPanel");e&&doZoom(.8,e.clientWidth/2,e.clientHeight/2)}function viewerReset(){var e,t,n,i=document.getElementById("originalPanel"),a=document.getElementById("originalImage");i&&a&&a.naturalWidth&&(e=i.clientWidth,i=i.clientHeight,t=a.naturalWidth,a=a.naturalHeight,n=Math.min(e/t,i/a),viewer.scale=n,viewer.tx=(e-t*n)/2,viewer.ty=(i-a*n)/2,applyViewerTransform())}function initViewer(){["originalPanel","processedPanel"].map(e=>document.getElementById(e)).filter(Boolean).forEach(i=>{i.addEventListener("wheel",e=>{e.preventDefault();var t=i.getBoundingClientRect(),n=e.clientX-t.left;doZoom(e.deltaY<0?1.12:1/1.12,n,e.clientY-t.top)},{passive:!1}),i.addEventListener("mousedown",e=>{0===e.button&&(viewer.isDragging=!0,viewer.startX=e.clientX,viewer.startY=e.clientY,viewer.startTx=viewer.tx,viewer.startTy=viewer.ty,e.preventDefault())})}),window.addEventListener("mousemove",e=>{viewer.isDragging&&(viewer.tx=viewer.startTx+(e.clientX-viewer.startX),viewer.ty=viewer.startTy+(e.clientY-viewer.startY),applyViewerTransform())}),window.addEventListener("mouseup",()=>{viewer.isDragging=!1})}document.addEventListener("DOMContentLoaded",()=>{initAccordion(),initViewer()});